#  Chapter Three: Basics
## 3.3: Native Data Structures

This section is long and deserves its own notebook. And it's important -- it's about data. [Take that for data!](https://www.youtube.com/watch?v=dfuVdja6lDU) 

In [1]:
using Pkg
Pkg.activate("juliadatascience")

  Activating project at `~/research/JuliaDataScience/notebooks/juliadatascience`


Computing languages have many different data structures, e.g. strings, lists, etc. Julia is no different. The specific data structures that we'll look at in this notebook are `String`, `Tuple`, `NamedTuple`, `UnitRange`, `Arrays`, `Pair`, `Dict`, `Symbol`. Some of these types might look familiar and some may not. Don't worry, Ryan, we'll figure it out. As I mentioend previously [(in Chapter Three notebook)](https://github.com/rtelmore/JuliaDataScience/blob/main/notebooks/03-julia-basics.ipynb), the `methodswith` function is super handy. Check out the first five methods that operate on `String`.

In [2]:
first(methodswith(String), 5)

[1] String(s::String) in Core at boot.jl:358
[2] Symbol(s::String) in Core at boot.jl:489
[3] ==(a::String, b::String) in Base at strings/string.jl:122
[4] ==(a::Union{SubString{String}, String}, b::Union{SubString{String}, String}) in Base at strings/substring.jl:107
[5] CanonicalIndexError(func::String, type) in Base at abstractarray.jl:1255

### 3.3.1: Broadcasting Operators and Functions

If you are familiar with R, you'll know that vectorization is an important concent for speeding up your code. The same is here in Julia, but it's called **broadcasting**. Vectorization is achieved in Julia using the dot operator (`.`). Look at a vectorized addition on a vector using `.+`. And what happens is we just try adding one to the vector.

In [3]:
[1, 2, 5] .+ 1

3-element Vector{Int64}:
 2
 3
 6

In [4]:
[1, 2, 5] + 1

LoadError: MethodError: no method matching +(::Vector{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Base.TwicePrecision, ::Number) at twiceprecision.jl:290
  ...

D'oh, we get an error. 

We can use these vectorization operations on our own functions as well. Consider the `logarithm` function that we used in the first part of this tutorial. You can load it in by calling the `include` function on a file I added to the repo, `03-functions.jl`. Note that I will add the functions from each chapter into their own `chapternumber-functions.jl` file. 

In [5]:
include("03-functions.jl")

compare_interpolate (generic function with 1 method)

In [6]:
logarithm.([1, 2, 3])

3-element Vector{Float64}:
 0.0
 0.6931471805599569
 1.0986122886681282

### 3.3.2: Functions with a bang !

It's common in Julia to append an exclamation point (a bang, or `!`) to function names that modify the function's arguments. Consider the follwing function. 

In [7]:
function add_one!(V)
    for i in eachindex(V)
        V[i] += 1
    end
    return nothing
end

add_one! (generic function with 1 method)

This function will add one to each element of the vector that is input into the function itself. Define a vector and use the `add_one!` function on this vector. 

In [8]:
my_data = [1, 2, 3]
add_one!(my_data)

In [9]:
my_data

3-element Vector{Int64}:
 2
 3
 4

### Strings

Everyone knows that strings are part of life as a data scientist. You need to know how to work with them. Strings can be defined using double quotes, double quotes on multiple lines, or a series of three double quotes (similar to python, IIRC). Examples:

In [10]:
typeof("Here be a string")

String

In [11]:
text = "
This is a big multiline string.
As you can see.
It is still a String to Julia.
"

"\nThis is a big multiline string.\nAs you can see.\nIt is still a String to Julia.\n"

In [12]:
s = """
    This is a big multiline string with a nested "quotation".
    As you can see.
    It is still a String to Julia.
    """

"This is a big multiline string with a nested \"quotation\".\nAs you can see.\nIt is still a String to Julia.\n"

Note that these strings don't look as awesome in the notebook as if they were printed in the Julia REPL.

#### String Concatenation

How do we put strings together, i.e. concatenate the strings? I'll be honest, this is a strange one for me. You can use either the `*` or `join` functions. Say what? Yep, here goes. 

In [13]:
hello = "Hello"
goodbye = "Goodbye"
hello * goodbye

"HelloGoodbye"

In [14]:
hello * " " * goodbye

"Hello Goodbye"

What in the sam hell is going on here? This looks nutty. You can do this with `join` as well. Still a little weird though.

In [15]:
join([hello, goodbye], " ")

"Hello Goodbye"

I'm not sure which I like better. I'll probably use the asterisk, but we'll see. 

#### String Interpolation

I'm not sure I've ever heard this phrase before, but I've used it quite often in both python and R. Basically, it's where you want to insert a string into another string as a variable. 

In [16]:
"$hello $goodbye"

"Hello Goodbye"

String interpolation works inside functions as well. This is super cool. Recall the `compare()` function that was defined previously. 

In [17]:
function compare_interpolate(a, b)
    if a < b
        "$a is less than $b"
    elseif a > b
        "$a is greater than $b"
    else
        "$a is equal to $b"
    end
end

compare_interpolate (generic function with 1 method)

In [18]:
compare_interpolate(1, 5)

"1 is less than 5"

In [19]:
compare_interpolate(3.14, 3.14)

"3.14 is equal to 3.14"

In [20]:
compare_interpolate(3.141, 3.14)

"3.141 is greater than 3.14"

#### 3.3.3.3 String Manipulations

I went down the regex wormhole the other day and, damn, what a hole that is. In any case, fortunately we aren't going to explore them here. Of course, you're welcome to use them in Julia, but they have some other friendly functions to make string manipulations a little easier (than regex). First, we are going to define a string and start working. 

In [21]:
julia_string = "Julia is an amazing open source programming language"

"Julia is an amazing open source programming language"

Let's look at `contains`, `startswith`, and `endswith` functions.

In [22]:
contains(julia_string, "amazing")

true

In [23]:
startswith(julia_string, "Julia")

true

In [24]:
startswith(julia_string, "source")

false

In [25]:
endswith(julia_string, "Julia")

false

In [26]:
endswith(julia_string, "language")

true

In [27]:
endswith(julia_string, "guage")

true

How about making strings into different cases, e.g. lower to upper, etc. 

In [28]:
lowercase(julia_string)

"julia is an amazing open source programming language"

In [29]:
uppercase(julia_string)

"JULIA IS AN AMAZING OPEN SOURCE PROGRAMMING LANGUAGE"

In [30]:
titlecase(julia_string)

"Julia Is An Amazing Open Source Programming Language"

In [31]:
uppercasefirst("julia is an amazing open source programming language")

"Julia is an amazing open source programming language"

We can replace strings within strings using the `replace` function. Note that we have to a new structure called the `pair`. 

In [32]:
replace(julia_string, "amazing" => "awesome")

"Julia is an awesome open source programming language"

In [33]:
julia_string

"Julia is an amazing open source programming language"

And finally we can split strings using the `split` function. 

In [34]:
split(julia_string, " ")

8-element Vector{SubString{String}}:
 "Julia"
 "is"
 "an"
 "amazing"
 "open"
 "source"
 "programming"
 "language"

#### 3.3.3.4 String Conversions

Converting from string to number and vice versa. 

In [35]:
string(1983)

"1983"

In [36]:
typeof(string(1983))

String

In [37]:
parse(Int64, "1983")

1983

In [38]:
typeof(parse(Int64, "1983"))

Int64

In [39]:
typeof(parse(Float64, "1983"))

Float64

In [40]:
parse(Float64, "1983")

1983.0

Another handy function is the `tryparse` function. This will try to do what the `parse` function would ordinarily do. If it can't, it will return `nothing`.

In [41]:
tryparse(Int64, "A string")

### 3.3.4 Tuple

Tuples are a super handy data structure in Julia. Why? Well, a lot of functions use tuples and there are a lot of functions in Julia. What makes a tuple a tuple? Well, tuples can hold multiple different types of data, they are fixed length, and are immutable. By immutable we mean that once they are defined, they can't be changed. Consider this `tuple`. 

In [42]:
my_tuple = (1, 3.14, "string")

(1, 3.14, "string")

Tuples are 1-based indexed. That is, the first element of the tuple is accessed with a 1 (similar to R) as opposed to a 0 (python). Here ya go. 

In [43]:
my_tuple[1]

1

In [44]:
my_tuple[3]

"string"

In [45]:
for t in my_tuple
    println(t)
end

1
3.14
string


Recall one of the previous functions that we defined previously, `add_multiply`. This function will return the sum and product of two numbers. The `return` statement in the function is listed as `return addition, multiplication`. The `a, b` is a `tuple` as well. 

In [46]:
add_multiply(3, 4)

(7, 12)

In [47]:
typeof(add_multiply(3, 4))

Tuple{Int64, Int64}

In [48]:
7, 12

(7, 12)

Anonymous functions use tuples as input. 

In [49]:
map((x, y) -> x^y, 2, 3)

8

In [50]:
map((x, y, z) -> x^y + z, 2, 3, 1)

9

### 3.3.5 Named Tuple

We can also name the objects within our tuples. They are still immutable.

In [51]:
named_tup = (i=1, f=3.14, s="Julia")

(i = 1, f = 3.14, s = "Julia")

In [52]:
named_tup.s

"Julia"

One way to build tuples is to first define variables and then construct the `tuple`. For example, 

In [53]:
i = 1
f = 3.14
s = "Julia"

my_quick_namedtuple = (; i, f, s)

(i = 1, f = 3.14, s = "Julia")

### 3.3.6 Ranges

A simple way to create a vector to iterate over is to use a `range`. Basically, if you want to create a sequence of numbers from x to y, use the `:` operator. Here ya go. 

In [54]:
1:10

1:10

To see what's in this range, we can loop over it using `for`.

In [55]:
[x for x in 1:10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

Maybe a more useful or illustrative example. 

In [56]:
typeof(15:20)

UnitRange{Int64}

In [57]:
[x for x in 15:20]

6-element Vector{Int64}:
 15
 16
 17
 18
 19
 20

Now, these do not have to be integers. We can create a sequence of numbers from x to y in increments of z by adding another argument (`:`) to the initial `:` call. 

In [58]:
0.0:0.2:1.0

0.0:0.2:1.0

In [59]:
typeof(0.0:0.2:1.0)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}

In [60]:
[x for x in 0.0:0.2:1.0]

6-element Vector{Float64}:
 0.0
 0.2
 0.4
 0.6
 0.8
 1.0

Or we can realize this vector using the `collect` function. 

In [61]:
collect(0.0:0.2:1.0)

6-element Vector{Float64}:
 0.0
 0.2
 0.4
 0.6
 0.8
 1.0

What if we add a step size that does not chop of the full range, e.g. 

In [62]:
collect(0:.3:1)

4-element Vector{Float64}:
 0.0
 0.3
 0.6
 0.9

In other words, it does what you'd expect. 

### 3.3.7 Array

Arrays are basically of two types: Vectors and Matrices. The generally hold objects of the same type, but it's not necessary. As mentioned in the book, they are the "bread and butter of data" science.

#### 3.3.7.1 Array Types

As said, there are two types: `Vector{T}` and `Matrix{T}` where `T` represents the type, e.g. `T` could be `Float64` or something. Note that `Vector{T}` is an alias to `Array{T, 1}` and `Matrix{T}` is an alias to `Array{T, 2}`. 

#### 3.3.7.2 Array Construction

How do we create these things? For example, suppose we are looping through something, doing some computing, and want to store our results in either a vector or matrix. We would probably want to pre-allocate memory for this sort of exercies. You could use the low-level `Vector{}` or `Matrix{}` functions. Suppose we want to allocate memory for a vector of length 10 or a 3x4 matrix, both of which we want as `Float64`. 

In [63]:
Vector{Float64}(undef, 10)

10-element Vector{Float64}:
 0.0
 2.351404383e-314
 2.378509528e-314
 0.0
 2.351404383e-314
 2.351390241e-314
 0.0
 2.351404383e-314
 2.3541489376e-314
 0.0

In [64]:
Matrix{Float64}(undef, 3, 4)

3×4 Matrix{Float64}:
 5.0e-324      1.0e-323      1.5e-323      2.5e-323
 5.0e-324      5.0e-324      5.0e-324      5.0e-324
 2.19824e-314  2.19824e-314  2.19824e-314  5.0e-324

There are some aliases for some special vectors/matrices, e.g. the identity. Note that you can specify these things as either Int or Float. Here ya go.

In [66]:
zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [69]:
zeros(Int64, 3, 4)

3×4 Matrix{Int64}:
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [71]:
ones(10)

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [72]:
ones(Int64, 10)

10-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [73]:
ones(3, 4)

3×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [74]:
ones(Int64, 3, 4)

3×4 Matrix{Int64}:
 1  1  1  1
 1  1  1  1
 1  1  1  1

If you pre-allocate memory and then want to add to a vector/matrix, you can use the `fill()` with a bang. 

In [75]:
my_matrix = Matrix{Float64}(undef, 2, 2)
fill!(my_matrix, 3.14)

2×2 Matrix{Float64}:
 3.14  3.14
 3.14  3.14

In [76]:
[[1 2]
 [3 4]]

2×2 Matrix{Int64}:
 1  2
 3  4

In [77]:
[[1 2][3 4]]

LoadError: MethodError: no method matching typed_hcat(::Matrix{Int64}, ::Int64, ::Int64)
Closest candidates are:
  typed_hcat(::Type{T}, ::Number...) where T at abstractarray.jl:1561
  typed_hcat(::Type{T}, ::Union{Number, LinearAlgebra.Adjoint{T, <:AbstractVector} where T}...) where T at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:229
  typed_hcat(::Type{T}, ::Union{Number, LinearAlgebra.Transpose{T, <:AbstractVector} where T}...) where T at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:230
  ...

In [78]:
Float64[[1 2]
        [3 4]]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [81]:
Float64[[1 2]
    [3 4]]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0